Update build-ipk.yml

diff --git a/.github/workflows/build-ipk.yml b/.github/workflows/build-ipk.yml
--- a/.github/workflows/build-ipk.yml
+++ b/.github/workflows/build-ipk.yml
@@ -20,13 +20,20 @@ jobs:
         sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
         sudo update-alternatives --set python3 /usr/bin/python3.8
         python3 --version  # Verify Python version
-        python3 -m ensurepip --upgrade
         python3 -m pip install --upgrade setuptools wheel  # Upgrade setuptools
 
     - name: Check Python and Distutils
       run: |
         python3 -c "import distutils; print(distutils.__file__)" || echo "distutils not found"
         python3 --version
+        python3 -m pip --version  # Check if pip is installed
+
+    - name: Install Python3 distutils if not found
+      run: |
+        if ! python3 -c "import distutils" &> /dev/null; then
+          echo "Distutils module not found, installing..."
+          sudo apt-get install -y python3-distutils
+        fi
 
     - name: Download ImmortalWRT SDK
       run: |
